"""add_writing_assistant

Revision ID: e3f8af2a579b
Revises: 4db19375ad2e
Create Date: 2026-07-02 17:09:48.474423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f8af2a579b'
down_revision: Union[str, Sequence[str], None] = '4db19375ad2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writing_assistant_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('action_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_assistant_messages_id'), 'writing_assistant_messages', ['id'], unique=False)
    op.create_index(op.f('ix_diagrams_id'), 'diagrams', ['id'], unique=False)
    op.create_index(op.f('ix_novelty_analyses_id'), 'novelty_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_paper_chat_messages_id'), 'paper_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_paper_comparisons_id'), 'paper_comparisons', ['id'], unique=False)
    op.create_index(op.f('ix_paper_evaluations_id'), 'paper_evaluations', ['id'], unique=False)
    op.add_column('projects', sa.Column('document_type', sa.String(), nullable=True))
    op.execute("UPDATE projects SET document_type = 'Research Thesis' WHERE document_type IS NULL")
    op.alter_column('projects', 'document_type', nullable=False)
    op.alter_column('projects', 'draft_title',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Untitled Draft'::character varying"))
    op.alter_column('projects', 'draft_content',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.alter_column('projects', 'draft_content',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('projects', 'draft_title',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Untitled Draft'::character varying"))
    op.drop_column('projects', 'document_type')
    op.drop_index(op.f('ix_paper_evaluations_id'), table_name='paper_evaluations')
    op.drop_index(op.f('ix_paper_comparisons_id'), table_name='paper_comparisons')
    op.drop_index(op.f('ix_paper_chat_messages_id'), table_name='paper_chat_messages')
    op.drop_index(op.f('ix_novelty_analyses_id'), table_name='novelty_analyses')
    op.drop_index(op.f('ix_diagrams_id'), table_name='diagrams')
    op.drop_index(op.f('ix_writing_assistant_messages_id'), table_name='writing_assistant_messages')
    op.drop_table('writing_assistant_messages')
    # ### end Alembic commands ###
